"""Create a concise, reproducible profile of the candidate dataset."""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from ai_recruiter.ingest import iter_candidates  # noqa: E402


def top_items(counter: Counter[str], limit: int = 15) -> list[tuple[str, int]]:
    return counter.most_common(limit)


def markdown_table(rows: list[tuple[str, int]], label: str) -> str:
    body = "\n".join(f"| {value} | {count:,} |" for value, count in rows)
    return f"| {label} | Candidates |\n|---|---:|\n{body}"


def profile(candidates_path: Path) -> str:
    count = india_count = open_to_work_count = 0
    relevant_title_count = recent_active_count = 0
    titles: Counter[str] = Counter()
    locations: Counter[str] = Counter()
    industries: Counter[str] = Counter()
    skill_names: Counter[str] = Counter()
    experience_bands: Counter[str] = Counter()
    missing_fields: Counter[str] = Counter()

    title_terms = (
        "machine learning",
        "ml engineer",
        "ai engineer",
        "data scientist",
        "applied scientist",
        "nlp engineer",
        "search engineer",
        "relevance",
    )

    for candidate in iter_candidates(candidates_path):
        count += 1
        profile_data = candidate.get("profile", {})
        signals = candidate.get("redrob_signals", {})

        title = str(profile_data.get("current_title", "Unknown"))
        location = str(profile_data.get("location", "Unknown"))
        industry = str(profile_data.get("current_industry", "Unknown"))
        years = profile_data.get("years_of_experience")

        titles[title] += 1
        locations[location] += 1
        industries[industry] += 1
        india_count += profile_data.get("country") == "India"
        open_to_work_count += signals.get("open_to_work_flag") is True
        relevant_title_count += any(term in title.lower() for term in title_terms)
        recent_active_count += str(signals.get("last_active_date", "")) >= "2026-03-01"

        if isinstance(years, (int, float)):
            band = "<5" if years < 5 else "5-9" if years <= 9 else "10+"
            experience_bands[band] += 1
        else:
            missing_fields["profile.years_of_experience"] += 1

        for skill in candidate.get("skills", []):
            if isinstance(skill, dict) and skill.get("name"):
                skill_names[str(skill["name"])] += 1

        for required_key in ("candidate_id", "profile", "career_history", "skills", "redrob_signals"):
            if required_key not in candidate:
                missing_fields[required_key] += 1

    return f"""# Candidate Data Profile

Generated by `scripts/profile_data.py` from `{candidates_path.name}`.

## Dataset scale

- Candidates: **{count:,}**
- India-based: **{india_count:,}** ({india_count / count:.1%})
- Open to work: **{open_to_work_count:,}** ({open_to_work_count / count:.1%})
- Active on or after 2026-03-01: **{recent_active_count:,}** ({recent_active_count / count:.1%})
- Candidates with a directly relevant current-title signal: **{relevant_title_count:,}** ({relevant_title_count / count:.1%})

The final figure is a deliberately broad title-based screen. It is a shortlist starting point, not a relevance label: strong candidates may use adjacent titles, and keyword-stuffed profiles may use relevant titles without credible career evidence.

## Experience distribution

{markdown_table([(band, experience_bands[band]) for band in ("<5", "5-9", "10+")], "Experience band (years)")}

## Most common current titles

{markdown_table(top_items(titles), "Current title")}

## Most common locations

{markdown_table(top_items(locations), "Location")}

## Most common industries

{markdown_table(top_items(industries), "Industry")}

## Most frequently listed skills

{markdown_table(top_items(skill_names), "Skill")}

## Data-quality checks

{markdown_table(top_items(missing_fields) or [("No missing required top-level fields detected", 0)], "Field")}

## Ranking implications

1. The pool is broad, so title and skill matching alone will be noisy.
2. The 5-9-year experience band should be a positive signal, not a hard cutoff.
3. Career-history descriptions should be the decisive evidence for production retrieval, ranking, evaluation, and product-shipping experience.
4. Behavioral signals should adjust a strong technical-fit score; they should not rescue a non-fit profile.
5. The next profiling pass should examine suspicious timeline and skill-duration combinations to detect honeypots.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidates", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    if not args.candidates.is_file():
        parser.error(f"Candidate file does not exist: {args.candidates}")

    report = profile(args.candidates)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")
    print(f"Wrote data profile for {args.candidates.name} to {args.out}")


if __name__ == "__main__":
    main()
